version: '3.8'
services:
  app:
    container_name: app-springboot-postgresql
    image: app-springboot-postgresql
    build: ./
    ports:
      - "8000:8080"
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=matches 
  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: dracula
      ADMINER_DEFAULT_DB_DRIVER: postgresql
    ports:
      - 8080:8080